# -*- coding: utf-8 -*-
from csvImporter.fields import IntegerField, CharField
from django.contrib.auth.models import User
from django.db import models
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from csvImporter.model import CsvModel
from report_forms.choices import FIELD_OF_REHAB, YES_NO_CHOICES, DISCHARGE_STATUS_CHOICES, DISCHARGE, IF_UNPLANNED_DISCHARGE

class r1(models.Model):
    patient_id                      = models.IntegerField(_('Patients ID'), unique=True)
    case_id                         = models.IntegerField(_('Case ID'))
    date_of_birth                   = models.DateField(_('Date of birth'))
    field_of_rehab                  = models.IntegerField(_('Professional field of rehabilitation'), max_length=1, choices=FIELD_OF_REHAB, default=0)
    field_of_rehab_other            = models.CharField(_('If other'), max_length=255, null=True, blank=True)
    date_of_admission               = models.DateField(_('Date of admission'))
    FIM_applied                     = models.IntegerField(_('FIM applied at admission'), max_length=1, choices=YES_NO_CHOICES, default=0)
    FIM_date_of_assess              = models.DateField(_('FIM date of assessment'), null=True, blank=True)
    FIM_score                       = models.FloatField(_('FIM value/score'), null=True, blank=True)
    BI_applied                      = models.IntegerField(_('Barthel index applied at admission'), max_length=1, choices=YES_NO_CHOICES, default=0)
    BI_date_of_assess               = models.DateField(_('Barthel index date of assessment'), null=True, blank=True)
    BI_score                        = models.FloatField(_('Barthel index value/score'), null=True, blank=True)
    SMWT_applied                    = models.IntegerField(_('6 minutes walk test applied at admission'), max_length=1, choices=YES_NO_CHOICES, default=0)
    SMWT_date_of_assess             = models.DateField(_('6 minutes walk test date of assessment'), null=True, blank=True)
    SMWT_score                      = models.FloatField(_('6 minutes walk test value/score'), null=True, blank=True)
    SF_applied                      = models.IntegerField(_('SF-36 applied at admission'), max_length=1, choices=YES_NO_CHOICES, default=0)
    SF_date_of_assess               = models.DateField(_('SF-36 date of assessment'), null=True, blank=True)
    SF_score                        = models.FloatField(_('SF-36 value/score'), null=True, blank=True)
    SAT_applied                     = models.IntegerField(_('SAT applied at admission'), max_length=1, choices=YES_NO_CHOICES, default=0)
    SAT_date_of_assess              = models.DateField(_('SAT date of assessment'), null=True, blank=True)
    SAT_score                       = models.FloatField(_('SAT value/score'), null=True, blank=True)
    FEV_applied                     = models.IntegerField(_('FEV-1 applied at admission'), max_length=1, choices=YES_NO_CHOICES, default=0)
    FEV_date_of_assess              = models.DateField(_('FEV-1 date of assessment'), null=True, blank=True)
    FEV_score                       = models.FloatField(_('FEV-1 value/score'), null=True, blank=True)
    AI_applied                      = models.IntegerField(_('ASIA impairment applied at admission'), max_length=1, choices=YES_NO_CHOICES, default=0)
    AI_date_of_assess               = models.DateField(_('ASIA impairment date of assessment'), null=True, blank=True)
    AI_score                        = models.FloatField(_('ASIA impairment value/score'), null=True, blank=True)
    SNC_applied                     = models.IntegerField(_('Standard neurological classification of spinal cord injury applied at admission'), max_length=1, choices=YES_NO_CHOICES, default=0)
    SNC_date_of_assess              = models.DateField(_('Standard neurological classification of spinal cord injury date of assessment'), null=True, blank=True)
    SNC_score                       = models.FloatField(_('Standard neurological classification of spinal cord injury value/score'), null=True, blank=True)
    SCI_applied                     = models.IntegerField(_('Spinal Cord Independence Measure applied at admission'), max_length=1, choices=YES_NO_CHOICES, default=0)
    SCI_date_of_assess              = models.DateField(_('Spinal Cord Independence Measure date of assessment'), null=True, blank=True)
    SCI_score                       = models.FloatField(_('Spinal Cord Independence Measure value/score'), null=True, blank=True)
    Other_applied                   = models.IntegerField(_('Other applied at admission'), max_length=1, choices=YES_NO_CHOICES, default=0)
    Other_name_of                   = models.CharField(_('Other name of functional assessment'), max_length=255, null=True, blank=True)
    Other_date_of_assess            = models.DateField(_('Other date of assessment'), null=True, blank=True)
    Other_score                     = models.FloatField(_('Other value/score'), null=True, blank=True)
    patient_discharge_status        = models.IntegerField(_('Patient discharge status'), max_length=1, default=0, choices=DISCHARGE_STATUS_CHOICES)
    discharge                       = models.IntegerField(_('Discharge'), max_length=1, default=0, choices=DISCHARGE)
    if_unplanned                    = models.IntegerField(_('If unplanned, the reason'), max_length=1, default=0, choices=IF_UNPLANNED_DISCHARGE, null=True, blank=True)
    date_of_discharge               = models.DateField(_('Date of discharge'))
    FIM_applied_discharge           = models.IntegerField(_('FIM applied at discharge'), max_length=1, choices=YES_NO_CHOICES, default=0)
    FIM_date_of_assess_discharge    = models.DateField(_('FIM date of assessment'), null=True, blank=True)
    FIM_score_discharge             = models.FloatField(_('FIM value/score'), null=True, blank=True)
    BI_applied_discharge            = models.IntegerField(_('Barthel index applied at discharge'), max_length=1, choices=YES_NO_CHOICES, default=0)
    BI_date_of_assess_discharge     = models.DateField(_('Barthel index date of assessment'), null=True, blank=True)
    BI_score_discharge              = models.FloatField(_('Barthel index value/score'), null=True, blank=True)
    SMWT_applied_discharge          = models.IntegerField(_('6 minutes walk test applied at discharge'), max_length=1, choices=YES_NO_CHOICES, default=0)
    SMWT_date_of_assess_discharge   = models.DateField(_('6 minutes walk test date of assessment'), null=True, blank=True)
    SMWT_score_discharge            = models.FloatField(_('6 minutes walk test value/score'), null=True, blank=True)
    SF_applied_discharge            = models.IntegerField(_('SF-36 applied at discharge'), max_length=1, choices=YES_NO_CHOICES, default=0)
    SF_date_of_assess_discharge     = models.DateField(_('SF-36 date of assessment'), null=True, blank=True)
    SF_score_discharge              = models.FloatField(_('SF-36 value/score'), null=True, blank=True)
    SAT_applied_discharge           = models.IntegerField(_('SAT applied at discharge'), max_length=1, choices=YES_NO_CHOICES, default=0)
    SAT_date_of_assess_discharge    = models.DateField(_('SAT date of assessment'), null=True, blank=True)
    SAT_score_discharge             = models.FloatField(_('SAT value/score'), null=True, blank=True)
    FEV_applied_discharge           = models.IntegerField(_('FEV-1 applied at discharge'), max_length=1, choices=YES_NO_CHOICES, default=0)
    FEV_date_of_assess_discharge    = models.DateField(_('FEV-1 date of assessment'), null=True, blank=True)
    FEV_score_discharge             = models.FloatField(_('FEV-1 value/score'), null=True, blank=True)
    AI_applied_discharge            = models.IntegerField(_('ASIA impairment applied at discharge'), max_length=1, choices=YES_NO_CHOICES, default=0)
    AI_date_of_assess_discharge     = models.DateField(_('ASIA impairment date of assessment'), null=True, blank=True)
    AI_score_discharge              = models.FloatField(_('ASIA impairment value/score'), null=True, blank=True)
    SNC_applied_discharge           = models.IntegerField(_('Standard neurological classification of spinal cord injury applied at discharge'), max_length=1, choices=YES_NO_CHOICES, default=0)
    SNC_date_of_assess_discharge    = models.DateField(_('Standard neurological classification of spinal cord injury date of assessment'), null=True, blank=True)
    SNC_score_discharge             = models.FloatField(_('Standard neurological classification of spinal cord injury value/score'), null=True, blank=True)
    SCI_applied_discharge           = models.IntegerField(_('Spinal Cord Independence Measure applied at discharge'), max_length=1, choices=YES_NO_CHOICES, default=0)
    SCI_date_of_assess_discharge    = models.DateField(_('Spinal Cord Independence Measure date of assessment'), null=True, blank=True)
    SCI_score_discharge             = models.FloatField(_('Spinal Cord Independence Measure value/score'), null=True, blank=True)
    Other_applied_discharge         = models.IntegerField(_('Other applied at discharge'), max_length=1, choices=YES_NO_CHOICES, default=0)
    Other_name_of_discharge         = models.CharField(_('Other name of functional assessment'), max_length=255, null=True, blank=True)
    Other_date_of_assess_discharge  = models.DateField(_('Other date of assessment'), null=True, blank=True)
    Other_score_discharge           = models.FloatField(_('Other value/score'), null=True, blank=True)
    added_on                        = models.DateTimeField(auto_now_add=True)
    added_by                        = models.ForeignKey(User, verbose_name=_('User'))

    def __unicode__(self):
        return str(self.patient_id)

    class Meta:
        verbose_name = _('Indicators for rehabilitation hospital and department')
        verbose_name_plural = _('Indicators for rehabilitation hospitals and departments')

class r1CSV(CsvModel):
    patient_id                      = IntegerField()
    case_id                         = IntegerField()
    date_of_birth                   = CharField()
    field_of_rehab                  = CharField()
    field_of_rehab_other            = CharField()
    date_of_admission               = CharField()
    FIM_applied                     = CharField()
    FIM_date_of_assess              = CharField()
    FIM_score                       = CharField()
    BI_applied                      = CharField()
    BI_date_of_assess               = CharField()
    BI_score                        = CharField()
    SMWT_applied                    = CharField()
    SMWT_date_of_assess             = CharField()
    SMWT_score                      = CharField()
    SF_applied                      = CharField()
    SF_date_of_assess               = CharField()
    SF_score                        = CharField()
    SAT_applied                     = CharField()
    SAT_date_of_assess              = CharField()
    SAT_score                       = CharField()
    FEV_applied                     = CharField()
    FEV_date_of_assess              = CharField()
    FEV_score                       = CharField()
    AI_applied                      = CharField()
    AI_date_of_assess               = CharField()
    AI_score                        = CharField()
    SNC_applied                     = CharField()
    SNC_date_of_assess              = CharField()
    SNC_score                       = CharField()
    SCI_applied                     = CharField()
    SCI_date_of_assess              = CharField()
    SCI_score                       = CharField()
    Other_applied                   = CharField()
    Other_name_of                   = CharField()
    Other_date_of_assess            = CharField()
    Other_score                     = CharField()
    patient_discharge_status        = CharField()
    discharge                       = CharField()
    if_unplanned                    = CharField()
    date_of_discharge               = CharField()
    FIM_applied_discharge           = CharField()
    FIM_date_of_assess_discharge    = CharField()
    FIM_score_discharge             = CharField()
    BI_applied_discharge            = CharField()
    BI_date_of_assess_discharge     = CharField()
    BI_score_discharge              = CharField()
    SMWT_applied_discharge          = CharField()
    SMWT_date_of_assess_discharge   = CharField()
    SMWT_score_discharge            = CharField()
    SF_applied_discharge            = CharField()
    SF_date_of_assess_discharge     = CharField()
    SF_score_discharge              = CharField()
    SAT_applied_discharge           = CharField()
    SAT_date_of_assess_discharge    = CharField()
    SAT_score_discharge             = CharField()
    FEV_applied_discharge           = CharField()
    FEV_date_of_assess_discharge    = CharField()
    FEV_score_discharge             = CharField()
    AI_applied_discharge            = CharField()
    AI_date_of_assess_discharge     = CharField()
    AI_score_discharge              = CharField()
    SNC_applied_discharge           = CharField()
    SNC_date_of_assess_discharge    = CharField()
    SNC_score_discharge             = CharField()
    SCI_applied_discharge           = CharField()
    SCI_date_of_assess_discharge    = CharField()
    SCI_score_discharge             = CharField()
    Other_applied_discharge         = CharField()
    Other_name_of_discharge         = CharField()
    Other_date_of_assess_discharge  = CharField()
    Other_score_discharge           = CharField()

    class Meta:
        delimiter = ";"

admin.site.register(r1)
